sudo: required
dist: trusty
matrix:
  include:
    - language: python
      python: 2.7
      before_install:
        - cd pai-management
      install:
        - pip install paramiko pyyaml jinja2 python-etcd kubernetes
      script:
        - python -m unittest discover test/
    - language: java
      jdk: oraclejdk8
      before_install:
        - cd frameworklauncher
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn clean test jacoco:report coveralls:report
    - language: java
      jdk: openjdk8
      before_install:
        - cd frameworklauncher
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn clean test jacoco:report coveralls:report
    - language: node_js
      node_js: 6
      env: NODE_ENV=test
      before_install:
        - cd rest-server
      install:
        - npm install
      script:
        - npm test
        - npm run coveralls
    - language: node_js
      node_js: 7
      env: NODE_ENV=test
      before_install:
        - cd rest-server
      install:
        - npm install
      script:
        - npm test
        - npm run coveralls
    - language: node_js
      node_js: 6
      before_install:
        - cd webportal
      install:
        - npm run yarn install
        - npm run build
      script:
        - npm test
    - language: node_js
      node_js: 7
      before_install:
        - cd webportal
      install:
        - npm run yarn install
        - npm run build
      script:
        - npm test
